#
# Shared keys
shared:
  # Add "common_merge_criteria" anchor
  # Use "*common_merge_criteria" alias to reference this anchor
  my_ci: &common_merge_criteria
    - "#approved-reviews-by>=1"
    - "#changes-requested-reviews-by=0"
    - "#review-threads-unresolved=0"
#
# Pull request rules https://docs.mergify.com/configuration/#pull-request-rules
# N.B. Evaluated in order defined

pull_request_rules:  # yamllint disable-line rule:key-ordering
  #
  # PR.1) Remove stale approvals or changes requests
  - actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
        message: New commit(s) added, removing existing approval(s)
        when: synchronize
    conditions:
      - base=main
    name: Remove outdated reviews
  #
  # PR.2) Require all conversations to be resolved
  - actions:
      comment:
        message: "This Pull Request needs all conversation threads to be resolved. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - question
    conditions:
      - "#review-threads-unresolved>0"
    name: Check for unresolved conversations before merging
  #
  # PR.3) If all conversations to be resolved, remove question label
  - actions:
      label:
        remove:
          - question
    conditions:
      - "#review-threads-unresolved=0"
    name: Remove question label from resolved conversations

  #
  # PR.4) Require all changes requested reviews to be resolved
  - actions:
      comment:
        message: "This Pull Request needs all changes requested to be resolved. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - changes requested
    conditions:
      - "#changes-requested-reviews-by>0"
    name: Check for unresolved changes requested before merging
  #
  # PR.5) If all changes requested are resolved, remove question label
  - actions:
      label:
        remove:
          - changes requested
    conditions:
      - "#changes-requested-reviews-by=0"
    name: Remove question label from resolved changes requested

  # PR.6) If Pull Request check fails, request resolution (prevent stalling the merge queue)
  - actions:
      comment:
        message: "This Pull Request needs all checks to run successfully. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - invalid
    conditions:
      - and:
          - base=main
          - label!=work in progress
          - label!=do not merge
          - updated-at<1 days ago
          - and: *common_merge_criteria
          - or:
              - -check-success="CI"
              - -check-success="CI (Ansible devel sanity Lint)"
              - -check-success="CI (Ansible devel sanity Sanity)"
              - -check-success="CI (Ansible devel sanity Units)"
              - -check-success="CI (Summary Code Coverage)"
    name: Request Pull Request check re-run
  #
  # PR.7) Merge Pull Request rule
  - actions:
      label:
        remove:
          - invalid
      queue:
    conditions:
      - base=main
      - label!=work in progress
      - label!=do not merge
      - check-success="CI"
      - check-success="CI (Ansible devel sanity Lint)"
      - check-success="CI (Ansible devel sanity Sanity)"
      - check-success="CI (Ansible devel sanity Units)"
      - check-success="CI (Summary Code Coverage)"
      - check-success="Lint Blue"
      # - check-success="Lint Green"
      - &id001
        and: *common_merge_criteria
    name: Automatic merge on approval for Pull Requests
  #
  # PR.8) Detect when Pull Request has conflicts and add conflicts label
  - actions:
      comment:
        message: "This Pull Request is now in conflict. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - conflict
    conditions:
      - conflict
    name: Warn on conflicts
  #
  # PR.9) Detect when Pull Request conflict is cleared and remove label
  - actions:
      label:
        remove:
          - conflict
    conditions:
      - -conflict
    name: Remove conflict label if not needed
  #
  # PR.10) Automatically close Pull Request after 14 days
  - actions:
      close:
        message: |
          This Pull Request looks stale. Feel free to reopen it if you think it's a mistake.
    conditions:
      - base=main
      - -closed
      - updated-at<14 days ago
    name: Close stale Pull Request
  #
  # PR.11) Detect when Pull Request is ready / awaiting review and add label
  - actions:
      label:
        add:
          - waiting for review
    conditions:
      - "#commented-reviews-by<1"
      - created-at<1 days ago
      - -draft
      # TODO: Check at least one change type is selected
      # Checklist
      # - body~=(?m)^- \[[xX]\] I have added unit tests that prove my fix is effective or that my feature works
    name: Pull Request is ready and waiting for review
  #
  # PR.12) Detect when Pull Request received review and remove label
  - actions:
      label:
        remove:
          - waiting for review
    conditions:
      - "#commented-reviews-by>=1"
      - -draft
    name: Remove waiting for review label if not needed
  #
  # PR.13) Detect when Pull Request includes a bug and add label
  - actions:
      label:
        add:
          - bug
    conditions:
      - body~=(?m)^- \[[xX]\] Bug fix \(non-breaking change which fixes an issue\)
    name: Add bug label
  #
  # PR.14) Detect when Pull Request no longer includes bug and remove label
  - actions:
      label:
        remove:
          - bug
    conditions:
      - body~=(?m)^- \[ \] Bug fix \(non-breaking change which fixes an issue\)
    name: Remove bug label

  #
  # PR.15) Detect when Pull Request includes enhancement and add label
  - actions:
      label:
        add:
          - enhancement
    conditions:
      - body~=(?m)^- \[[xX]\] New feature \(non-breaking change which adds functionality\)
    name: add enhancement label
  #
  # PR.16) Detect when Pull Request no longer includes enhancement and remove label
  - actions:
      label:
        remove:
          - enhancement
    conditions:
      - body~=(?m)^- \[ \] New feature \(non-breaking change which adds functionality\)
    name: remove enhancement label

  #
  # PR.17) Detect when Pull Request includes documentation updates and add label
  - actions:
      label:
        add:
          - documentation
    conditions:
      - body~=(?m)^- \[[xX]\] Documentation update
    name: add documentation label
  #
  # PR.18) Detect when Pull Request no longer includes documentation updates and remove label
  - actions:
      label:
        remove:
          - documentation
    conditions:
      - body~=(?m)^- \[ \] Documentation update
    name: remove documentation label

  #
  # PR.19) Detect when Pull Request includes tests update and add label
  - actions:
      label:
        add:
          - test update
    conditions:
      - body~=(?m)^- \[[xX]\] Tests update
    name: Add test update label
  #
  # PR.20) Detect when Pull Request no longer includes tests update and remove label
  - actions:
      label:
        remove:
          - test update
    conditions:
      - body~=(?m)^- \[ \] Tests update
    name: remove test update label

  #
  # PR.21) Detect when Pull Request includes refactoring and add label
  - actions:
      label:
        add:
          - refactor
    conditions:
      - body~=(?m)^- \[[xX]\] Refactor
    name: add refactor label
  #
  # PR.22) Detect when Pull Request no longer includes refactoring and remove label
  - actions:
      label:
        remove:
          - refactor
    conditions:
      - body~=(?m)^- \[ \] Refactor
    name: remove refactor label
#
# Merge queue rules https://docs.mergify.com/actions/queue/#queue-rules
queue_rules:  # yamllint disable-line rule:key-ordering
  #
  # Q.1) Add this Pull Request to the merge queue
  - name: default
    queue_conditions:
      - base=main
      - label!=work in progress
      - label!=do not merge
      - check-success="CI"
      - check-success="CI (Ansible devel sanity Lint)"
      - check-success="CI (Ansible devel sanity Sanity)"
      - check-success="CI (Ansible devel sanity Units)"
      - check-success="CI (Summary Code Coverage)"
      - check-success="Lint Blue"
      - *id001
    merge_conditions:
      - base=main
      - and: *common_merge_criteria
    commit_message_template: "{{ commits[0] }}"
    merge_method: squash
